# Generated by Django 5.0.3 on 2024-03-15 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='medical_records/'),
            preserve_default=False,
        ),
    ]
